export const bikes = [
    { 
        id: 1, 
        name: 'Ducati V4 Panigale', 
        power: '30 kW', 
        torque: '25 Nm', 
        topSpeed: '120 km/h', 
        colors: ['Red', 'Blue', 'Black'], 
        enginePower: '300 cc', 
        weight: '150 kg',
        fuelType: 'Petrol',
        description: 'A versatile bike suitable for both city rides and longer journeys.',
        image: './bikeImages/bike1.png' 
    },
    { 
        id: 2, 
        name: 'Kawasaki H2R Street Racer', 
        power: '35 kW', 
        torque: '28 Nm', 
        topSpeed: '130 km/h', 
        colors: ['Green', 'Yellow'], 
        enginePower: '350 cc', 
        weight: '160 kg',
        fuelType: 'Petrol',
        description: 'Ideal for sport riders looking for a balance between performance and comfort.',
        image: './bikeImages/bike2.png' 
    },
    { 
        id: 3, 
        name: 'Kawasaki Ninja 600', 
        power: '40 kW', 
        torque: '30 Nm', 
        topSpeed: '140 km/h', 
        colors: ['Black', 'White', 'Silver'], 
        enginePower: '400 cc', 
        weight: '170 kg',
        fuelType: 'Petrol',
        description: 'A powerful bike that delivers thrilling performance on the road.',
        image: './bikeImages/bike3.png' 
    },
    { 
        id: 4, 
        name: 'Kawasaki Z900', 
        power: '45 kW', 
        torque: '32 Nm', 
        topSpeed: '150 km/h', 
        colors: ['Orange', 'Purple'], 
        enginePower: '450 cc', 
        weight: '180 kg',
        fuelType: 'Petrol',
        description: 'A stylish bike with a sporty design, perfect for city commuting.',
        image: './bikeImages/bike4.png' 
    },
    { 
        id: 5, 
        name: 'Triumph Bonneville T100', 
        power: '50 kW', 
        torque: '35 Nm', 
        topSpeed: '160 km/h', 
        colors: ['Blue', 'Grey', 'White'], 
        enginePower: '500 cc', 
        weight: '190 kg',
        fuelType: 'Petrol',
        description: 'Designed for riders who crave speed and adventure, with advanced features.',
        image: './bikeImages/bike5.avif' 
    },
    { 
        id: 6, 
        name: 'Triumph Truxton', 
        power: '55 kW', 
        torque: '40 Nm', 
        topSpeed: '170 km/h', 
        colors: ['Black', 'Red'], 
        enginePower: '600 cc', 
        weight: '200 kg',
        fuelType: 'Petrol',
        description: 'A high-performance bike with cutting-edge technology and design.',
        image: './bikeImages/bike6.avif' 
    },
    { 
        id: 7, 
        name: 'Harley Davidson FATBOY', 
        power: '60 kW', 
        torque: '45 Nm', 
        topSpeed: '180 km/h', 
        colors: ['Blue', 'Yellow'], 
        enginePower: '650 cc', 
        weight: '210 kg',
        fuelType: 'Petrol',
        description: 'Perfect for touring with exceptional comfort and storage options.',
        image: './bikeImages/bike7.png' 
    },
];
